import type { DeliveryDefinition } from '../types/match.types';
export const DELIVERIES: readonly DeliveryDefinition[] = [
  { id:'delivery.fast.stock', displayName:'Fast Stock Ball', eligibleStyles:['right_arm_fast','left_arm_fast'], defaultLength:'good', difficulty:.20, controlPenalty:.00, movementProfile:'seam', movementStrength:.18, staminaCost:5, idealAttribute:'pace' },
  { id:'delivery.fast.outswing', displayName:'Outswinger', eligibleStyles:['right_arm_fast','left_arm_fast','right_arm_medium','left_arm_medium'], defaultLength:'full', difficulty:.40, controlPenalty:.10, movementProfile:'swing_out', movementStrength:.40, staminaCost:5, idealAttribute:'swing' },
  { id:'delivery.fast.inswing', displayName:'Inswinger', eligibleStyles:['right_arm_fast','left_arm_fast','right_arm_medium','left_arm_medium'], defaultLength:'full', difficulty:.42, controlPenalty:.11, movementProfile:'swing_in', movementStrength:.40, staminaCost:5, idealAttribute:'swing' },
  { id:'delivery.fast.cutter', displayName:'Cutter', eligibleStyles:['right_arm_fast','left_arm_fast','right_arm_medium','left_arm_medium'], defaultLength:'good', difficulty:.48, controlPenalty:.13, movementProfile:'cutter', movementStrength:.34, staminaCost:4, idealAttribute:'variation' },
  { id:'delivery.fast.slower', displayName:'Slower Ball', eligibleStyles:['right_arm_fast','left_arm_fast','right_arm_medium','left_arm_medium'], defaultLength:'good', difficulty:.36, controlPenalty:.09, movementProfile:'slower', movementStrength:.25, staminaCost:3, idealAttribute:'variation' },
  { id:'delivery.fast.bouncer', displayName:'Bouncer', eligibleStyles:['right_arm_fast','left_arm_fast'], defaultLength:'bouncer', difficulty:.45, controlPenalty:.12, movementProfile:'none', movementStrength:.05, staminaCost:6, idealAttribute:'pace' },
  { id:'delivery.fast.yorker', displayName:'Yorker', eligibleStyles:['right_arm_fast','left_arm_fast','right_arm_medium','left_arm_medium'], defaultLength:'yorker', difficulty:.55, controlPenalty:.18, movementProfile:'none', movementStrength:.05, staminaCost:6, idealAttribute:'accuracy' },
  { id:'delivery.spin.stock_off', displayName:'Stock Off-break', eligibleStyles:['off_spin','left_arm_orthodox'], defaultLength:'good', difficulty:.22, controlPenalty:.02, movementProfile:'off_break', movementStrength:.40, staminaCost:3, idealAttribute:'spin' },
  { id:'delivery.spin.stock_leg', displayName:'Stock Leg-break', eligibleStyles:['leg_spin','left_arm_wrist_spin'], defaultLength:'good', difficulty:.28, controlPenalty:.05, movementProfile:'leg_break', movementStrength:.46, staminaCost:3, idealAttribute:'spin' },
  { id:'delivery.spin.arm_ball', displayName:'Arm Ball', eligibleStyles:['off_spin','left_arm_orthodox'], defaultLength:'good', difficulty:.42, controlPenalty:.10, movementProfile:'none', movementStrength:.08, staminaCost:3, idealAttribute:'variation' },
  { id:'delivery.spin.googly', displayName:'Googly', eligibleStyles:['leg_spin','left_arm_wrist_spin'], defaultLength:'good', difficulty:.58, controlPenalty:.17, movementProfile:'googly', movementStrength:.48, staminaCost:4, idealAttribute:'variation' },
  { id:'delivery.spin.top_spinner', displayName:'Top Spinner', eligibleStyles:['off_spin','leg_spin','left_arm_orthodox','left_arm_wrist_spin'], defaultLength:'good', difficulty:.46, controlPenalty:.12, movementProfile:'top_spin', movementStrength:.40, staminaCost:4, idealAttribute:'variation' },
  { id:'delivery.spin.flipper', displayName:'Flipper', eligibleStyles:['leg_spin','left_arm_wrist_spin'], defaultLength:'full', difficulty:.68, controlPenalty:.22, movementProfile:'top_spin', movementStrength:.36, staminaCost:5, idealAttribute:'variation' },
  { id:'delivery.medium.seam', displayName:'Medium Seam', eligibleStyles:['right_arm_medium','left_arm_medium'], defaultLength:'good', difficulty:.24, controlPenalty:.02, movementProfile:'seam', movementStrength:.30, staminaCost:3, idealAttribute:'seam' },
];
