import type { EquipmentItem } from '../types/item.types';
export const ITEMS: readonly EquipmentItem[] = [
  { id:'item.bat.street_willow_01', category:'equipment', slot:'bat', name:'Street Willow', description:'Balanced starter bat.', rarity:'common', levelRequirement:1, purchasePrice:{currency:'coins',amount:350}, sellable:true, cosmeticOnly:false, maxUpgradeLevel:5, baseModifiers:[{stat:'batting.power',flatBonus:1},{stat:'batting.timing',flatBonus:1}], upgradeModifierPerLevel:[{stat:'batting.power',flatBonus:.3}], iconAssetId:'asset.icon.bat.street_willow_01', modelAssetId:'asset.model.bat.street_willow_01' },
  { id:'item.bat.club_edge_01', category:'equipment', slot:'bat', name:'Club Edge', description:'Control-focused club bat.', rarity:'uncommon', levelRequirement:6, purchasePrice:{currency:'coins',amount:950}, sellable:true, cosmeticOnly:false, maxUpgradeLevel:7, baseModifiers:[{stat:'batting.placement',flatBonus:2},{stat:'batting.timing',flatBonus:1}], upgradeModifierPerLevel:[{stat:'batting.placement',flatBonus:.35}], iconAssetId:'asset.icon.bat.club_edge_01', modelAssetId:'asset.model.bat.club_edge_01' },
  { id:'item.bat.pro_willow_01', category:'equipment', slot:'bat', name:'Pro Willow', description:'High-quality bat with a larger effective sweet spot.', rarity:'rare', levelRequirement:14, purchasePrice:{currency:'coins',amount:2400}, sellable:true, cosmeticOnly:false, maxUpgradeLevel:10, baseModifiers:[{stat:'batting.power',flatBonus:2},{stat:'batting.timing',flatBonus:2},{stat:'batting.placement',flatBonus:1}], upgradeModifierPerLevel:[{stat:'batting.power',flatBonus:.3},{stat:'batting.timing',flatBonus:.2}], iconAssetId:'asset.icon.bat.pro_willow_01', modelAssetId:'asset.model.bat.pro_willow_01' },
  { id:'item.helmet.core_guard_01', category:'equipment', slot:'helmet', name:'Core Guard', description:'Protective helmet with minimal gameplay impact.', rarity:'common', levelRequirement:1, purchasePrice:{currency:'coins',amount:300}, sellable:true, cosmeticOnly:false, maxUpgradeLevel:5, baseModifiers:[{stat:'physical.reflex',flatBonus:.5}], upgradeModifierPerLevel:[], iconAssetId:'asset.icon.helmet.core_guard_01', modelAssetId:'asset.model.helmet.core_guard_01' },
  { id:'item.gloves.quick_touch_01', category:'equipment', slot:'gloves', name:'Quick Touch Gloves', description:'Light gloves supporting control.', rarity:'uncommon', levelRequirement:4, purchasePrice:{currency:'coins',amount:650}, sellable:true, cosmeticOnly:false, maxUpgradeLevel:6, baseModifiers:[{stat:'batting.timing',flatBonus:1}], upgradeModifierPerLevel:[{stat:'batting.timing',flatBonus:.15}], iconAssetId:'asset.icon.gloves.quick_touch_01', modelAssetId:'asset.model.gloves.quick_touch_01' },
  { id:'item.pads.mobile_guard_01', category:'equipment', slot:'pads', name:'Mobile Guard Pads', description:'Lightweight pads.', rarity:'uncommon', levelRequirement:4, purchasePrice:{currency:'coins',amount:650}, sellable:true, cosmeticOnly:false, maxUpgradeLevel:6, baseModifiers:[{stat:'physical.agility',flatBonus:1}], upgradeModifierPerLevel:[{stat:'physical.agility',flatBonus:.15}], iconAssetId:'asset.icon.pads.mobile_guard_01', modelAssetId:'asset.model.pads.mobile_guard_01' },
  { id:'item.shoes.sprint_spikes_01', category:'equipment', slot:'shoes', name:'Sprint Spikes', description:'Traction-focused cricket shoes.', rarity:'rare', levelRequirement:10, purchasePrice:{currency:'coins',amount:1600}, sellable:true, cosmeticOnly:false, maxUpgradeLevel:8, baseModifiers:[{stat:'physical.agility',flatBonus:2},{stat:'physical.recovery',flatBonus:1}], upgradeModifierPerLevel:[{stat:'physical.agility',flatBonus:.15}], iconAssetId:'asset.icon.shoes.sprint_spikes_01', modelAssetId:'asset.model.shoes.sprint_spikes_01' },
  { id:'item.jersey.midnight_01', category:'cosmetic', slot:'jersey', name:'Midnight Jersey', description:'Cosmetic jersey.', rarity:'rare', levelRequirement:1, purchasePrice:{currency:'gems',amount:80}, sellable:false, cosmeticOnly:true, maxUpgradeLevel:0, baseModifiers:[], upgradeModifierPerLevel:[], iconAssetId:'asset.icon.jersey.midnight_01', modelAssetId:'asset.model.jersey.midnight_01' },
  { id:'item.bat_grip.neon_blue_01', category:'cosmetic', slot:'bat_grip', name:'Neon Blue Grip', description:'Cosmetic bat grip.', rarity:'uncommon', levelRequirement:1, purchasePrice:{currency:'gems',amount:30}, sellable:false, cosmeticOnly:true, maxUpgradeLevel:0, baseModifiers:[], upgradeModifierPerLevel:[], iconAssetId:'asset.icon.grip.neon_blue_01', modelAssetId:'asset.model.grip.neon_blue_01' },
  { id:'item.bat_sticker.legacy_gold_01', category:'cosmetic', slot:'bat_sticker', name:'Legacy Gold Sticker', description:'Premium cosmetic bat sticker.', rarity:'epic', levelRequirement:1, purchasePrice:{currency:'gems',amount:120}, sellable:false, cosmeticOnly:true, maxUpgradeLevel:0, baseModifiers:[], upgradeModifierPerLevel:[], iconAssetId:'asset.icon.sticker.legacy_gold_01', modelAssetId:'asset.model.sticker.legacy_gold_01' },
];
