import type { EquipmentItem } from '../types/item.types';
export const ITEMS: readonly EquipmentItem[] = [
  {
    id: 'item.bat.street_willow_01',
    category: 'equipment',
    slot: 'bat',
    name: 'Street Willow',
    description: 'Balanced starter bat.',
    rarity: 'common',
    levelRequirement: 1,
    purchasePrice: { currency: 'coins', amount: 350 },
    sellable: true,
    cosmeticOnly: false,
    maxUpgradeLevel: 5,
    baseModifiers: [
      { stat: 'batting.power', flatBonus: 1 },
      { stat: 'batting.timing', flatBonus: 1 },
    ],
    upgradeModifierPerLevel: [{ stat: 'batting.power', flatBonus: 0.3 }],
    iconAssetId: 'asset.icon.bat.street_willow_01',
    modelAssetId: 'asset.model.bat.street_willow_01',
  },
  {
    id: 'item.bat.backyard_ash_01',
    category: 'equipment',
    slot: 'bat',
    name: 'Backyard Ash',
    description: 'Forgiving practice bat with a steady feel.',
    rarity: 'common',
    levelRequirement: 1,
    purchasePrice: { currency: 'coins', amount: 400 },
    sellable: true,
    cosmeticOnly: false,
    maxUpgradeLevel: 5,
    baseModifiers: [
      { stat: 'batting.placement', flatBonus: 1 },
      { stat: 'batting.defence', flatBonus: 1 },
    ],
    upgradeModifierPerLevel: [{ stat: 'batting.defence', flatBonus: 0.25 }],
    iconAssetId: 'asset.icon.bat.backyard_ash_01',
    modelAssetId: 'asset.model.bat.backyard_ash_01',
  },
  {
    id: 'item.bat.club_edge_01',
    category: 'equipment',
    slot: 'bat',
    name: 'Club Edge',
    description: 'Control-focused club bat.',
    rarity: 'uncommon',
    levelRequirement: 6,
    purchasePrice: { currency: 'coins', amount: 950 },
    sellable: true,
    cosmeticOnly: false,
    maxUpgradeLevel: 7,
    baseModifiers: [
      { stat: 'batting.placement', flatBonus: 2 },
      { stat: 'batting.timing', flatBonus: 1 },
    ],
    upgradeModifierPerLevel: [{ stat: 'batting.placement', flatBonus: 0.35 }],
    iconAssetId: 'asset.icon.bat.club_edge_01',
    modelAssetId: 'asset.model.bat.club_edge_01',
  },
  {
    id: 'item.bat.pro_willow_01',
    category: 'equipment',
    slot: 'bat',
    name: 'Pro Willow',
    description: 'High-quality bat with a larger effective sweet spot.',
    rarity: 'rare',
    levelRequirement: 14,
    purchasePrice: { currency: 'coins', amount: 2400 },
    sellable: true,
    cosmeticOnly: false,
    maxUpgradeLevel: 10,
    baseModifiers: [
      { stat: 'batting.power', flatBonus: 2 },
      { stat: 'batting.timing', flatBonus: 2 },
      { stat: 'batting.placement', flatBonus: 1 },
    ],
    upgradeModifierPerLevel: [
      { stat: 'batting.power', flatBonus: 0.3 },
      { stat: 'batting.timing', flatBonus: 0.2 },
    ],
    iconAssetId: 'asset.icon.bat.pro_willow_01',
    modelAssetId: 'asset.model.bat.pro_willow_01',
  },
  {
    id: 'item.helmet.core_guard_01',
    category: 'equipment',
    slot: 'helmet',
    name: 'Core Guard',
    description: 'Protective helmet with minimal gameplay impact.',
    rarity: 'common',
    levelRequirement: 1,
    purchasePrice: { currency: 'coins', amount: 300 },
    sellable: true,
    cosmeticOnly: false,
    maxUpgradeLevel: 5,
    baseModifiers: [{ stat: 'physical.reflex', flatBonus: 0.5 }],
    upgradeModifierPerLevel: [],
    iconAssetId: 'asset.icon.helmet.core_guard_01',
    modelAssetId: 'asset.model.helmet.core_guard_01',
  },
  {
    id: 'item.gloves.quick_touch_01',
    category: 'equipment',
    slot: 'gloves',
    name: 'Quick Touch Gloves',
    description: 'Light gloves supporting control.',
    rarity: 'uncommon',
    levelRequirement: 4,
    purchasePrice: { currency: 'coins', amount: 650 },
    sellable: true,
    cosmeticOnly: false,
    maxUpgradeLevel: 6,
    baseModifiers: [{ stat: 'batting.timing', flatBonus: 1 }],
    upgradeModifierPerLevel: [{ stat: 'batting.timing', flatBonus: 0.15 }],
    iconAssetId: 'asset.icon.gloves.quick_touch_01',
    modelAssetId: 'asset.model.gloves.quick_touch_01',
  },
  {
    id: 'item.pads.mobile_guard_01',
    category: 'equipment',
    slot: 'pads',
    name: 'Mobile Guard Pads',
    description: 'Lightweight pads.',
    rarity: 'uncommon',
    levelRequirement: 4,
    purchasePrice: { currency: 'coins', amount: 650 },
    sellable: true,
    cosmeticOnly: false,
    maxUpgradeLevel: 6,
    baseModifiers: [{ stat: 'physical.agility', flatBonus: 1 }],
    upgradeModifierPerLevel: [{ stat: 'physical.agility', flatBonus: 0.15 }],
    iconAssetId: 'asset.icon.pads.mobile_guard_01',
    modelAssetId: 'asset.model.pads.mobile_guard_01',
  },
  {
    id: 'item.shoes.sprint_spikes_01',
    category: 'equipment',
    slot: 'shoes',
    name: 'Sprint Spikes',
    description: 'Traction-focused cricket shoes.',
    rarity: 'rare',
    levelRequirement: 10,
    purchasePrice: { currency: 'coins', amount: 1600 },
    sellable: true,
    cosmeticOnly: false,
    maxUpgradeLevel: 8,
    baseModifiers: [
      { stat: 'physical.agility', flatBonus: 2 },
      { stat: 'physical.recovery', flatBonus: 1 },
    ],
    upgradeModifierPerLevel: [{ stat: 'physical.agility', flatBonus: 0.15 }],
    iconAssetId: 'asset.icon.shoes.sprint_spikes_01',
    modelAssetId: 'asset.model.shoes.sprint_spikes_01',
  },
  {
    id: 'item.jersey.midnight_01',
    category: 'cosmetic',
    slot: 'jersey',
    name: 'Midnight Jersey',
    description: 'Cosmetic jersey.',
    rarity: 'rare',
    levelRequirement: 1,
    purchasePrice: { currency: 'gems', amount: 80 },
    sellable: false,
    cosmeticOnly: true,
    maxUpgradeLevel: 0,
    baseModifiers: [],
    upgradeModifierPerLevel: [],
    iconAssetId: 'asset.icon.jersey.midnight_01',
    modelAssetId: 'asset.model.jersey.midnight_01',
  },
  {
    id: 'item.bat_grip.neon_blue_01',
    category: 'cosmetic',
    slot: 'bat_grip',
    name: 'Neon Blue Grip',
    description: 'Cosmetic bat grip.',
    rarity: 'uncommon',
    levelRequirement: 1,
    purchasePrice: { currency: 'gems', amount: 30 },
    sellable: false,
    cosmeticOnly: true,
    maxUpgradeLevel: 0,
    baseModifiers: [],
    upgradeModifierPerLevel: [],
    iconAssetId: 'asset.icon.grip.neon_blue_01',
    modelAssetId: 'asset.model.grip.neon_blue_01',
  },
  {
    id: 'item.bat_sticker.legacy_gold_01',
    category: 'cosmetic',
    slot: 'bat_sticker',
    name: 'Legacy Gold Sticker',
    description: 'Premium cosmetic bat sticker.',
    rarity: 'epic',
    levelRequirement: 1,
    purchasePrice: { currency: 'gems', amount: 120 },
    sellable: false,
    cosmeticOnly: true,
    maxUpgradeLevel: 0,
    baseModifiers: [],
    upgradeModifierPerLevel: [],
    iconAssetId: 'asset.icon.sticker.legacy_gold_01',
    modelAssetId: 'asset.model.sticker.legacy_gold_01',
  },
  {
    id: 'item.gloves.starter_01',
    category: 'equipment',
    slot: 'gloves',
    name: 'Starter Gloves',
    description: 'Basic batting gloves issued to every new cricketer.',
    rarity: 'common',
    levelRequirement: 1,
    sellable: false,
    cosmeticOnly: false,
    maxUpgradeLevel: 3,
    baseModifiers: [],
    upgradeModifierPerLevel: [],
    iconAssetId: 'asset.icon.gloves.starter_01',
    modelAssetId: 'asset.model.gloves.starter_01',
  },
  {
    id: 'item.pads.starter_01',
    category: 'equipment',
    slot: 'pads',
    name: 'Starter Pads',
    description: 'Basic leg guards issued to every new cricketer.',
    rarity: 'common',
    levelRequirement: 1,
    sellable: false,
    cosmeticOnly: false,
    maxUpgradeLevel: 3,
    baseModifiers: [],
    upgradeModifierPerLevel: [],
    iconAssetId: 'asset.icon.pads.starter_01',
    modelAssetId: 'asset.model.pads.starter_01',
  },
  {
    id: 'item.shoes.starter_01',
    category: 'equipment',
    slot: 'shoes',
    name: 'Starter Shoes',
    description: 'Basic cricket shoes issued to every new cricketer.',
    rarity: 'common',
    levelRequirement: 1,
    sellable: false,
    cosmeticOnly: false,
    maxUpgradeLevel: 3,
    baseModifiers: [],
    upgradeModifierPerLevel: [],
    iconAssetId: 'asset.icon.shoes.starter_01',
    modelAssetId: 'asset.model.shoes.starter_01',
  },
  {
    id: 'item.jersey.starter_01',
    category: 'cosmetic',
    slot: 'jersey',
    name: 'Academy Jersey',
    description: 'Plain academy jersey.',
    rarity: 'common',
    levelRequirement: 1,
    sellable: false,
    cosmeticOnly: true,
    maxUpgradeLevel: 0,
    baseModifiers: [],
    upgradeModifierPerLevel: [],
    iconAssetId: 'asset.icon.jersey.starter_01',
    modelAssetId: 'asset.model.jersey.starter_01',
  },
  {
    id: 'item.pants.starter_01',
    category: 'cosmetic',
    slot: 'pants',
    name: 'Academy Trousers',
    description: 'Plain academy trousers.',
    rarity: 'common',
    levelRequirement: 1,
    sellable: false,
    cosmeticOnly: true,
    maxUpgradeLevel: 0,
    baseModifiers: [],
    upgradeModifierPerLevel: [],
    iconAssetId: 'asset.icon.pants.starter_01',
    modelAssetId: 'asset.model.pants.starter_01',
  },
];
