import type { ShotDefinition } from '../types/match.types';
export const SHOTS: readonly ShotDefinition[] = [
  {
    id: 'shot.forward_defensive',
    displayName: 'Forward Defensive',
    category: 'defensive',
    idealLines: ['off_stump', 'middle'],
    idealLengths: ['full', 'good'],
    preferredFoot: 'front',
    risk: 0.08,
    powerMultiplier: 0.45,
    timingDifficulty: 0.25,
    directionDegrees: [-18, 18],
    animationAssetKey: 'anim.bat.forward_defensive',
  },
  {
    id: 'shot.back_foot_defensive',
    displayName: 'Back-foot Defensive',
    category: 'defensive',
    idealLines: ['outside_off', 'off_stump', 'middle'],
    idealLengths: ['good', 'short'],
    preferredFoot: 'back',
    risk: 0.1,
    powerMultiplier: 0.48,
    timingDifficulty: 0.28,
    directionDegrees: [-25, 25],
    animationAssetKey: 'anim.bat.back_foot_defensive',
  },
  {
    id: 'shot.straight_drive',
    displayName: 'Straight Drive',
    category: 'drive',
    idealLines: ['off_stump', 'middle'],
    idealLengths: ['full'],
    preferredFoot: 'front',
    risk: 0.22,
    powerMultiplier: 1.0,
    timingDifficulty: 0.42,
    directionDegrees: [-12, 12],
    animationAssetKey: 'anim.bat.straight_drive',
  },
  {
    id: 'shot.cover_drive',
    displayName: 'Cover Drive',
    category: 'drive',
    idealLines: ['wide_off', 'outside_off', 'off_stump'],
    idealLengths: ['full', 'good'],
    preferredFoot: 'front',
    risk: 0.3,
    powerMultiplier: 1.02,
    timingDifficulty: 0.48,
    directionDegrees: [25, 58],
    animationAssetKey: 'anim.bat.cover_drive',
  },
  {
    id: 'shot.on_drive',
    displayName: 'On Drive',
    category: 'drive',
    idealLines: ['middle', 'leg'],
    idealLengths: ['full'],
    preferredFoot: 'front',
    risk: 0.28,
    powerMultiplier: 1.02,
    timingDifficulty: 0.47,
    directionDegrees: [-48, -15],
    animationAssetKey: 'anim.bat.on_drive',
  },
  {
    id: 'shot.flick',
    displayName: 'Flick',
    category: 'drive',
    idealLines: ['middle', 'leg', 'wide_leg'],
    idealLengths: ['full', 'good'],
    preferredFoot: 'either',
    risk: 0.26,
    powerMultiplier: 0.92,
    timingDifficulty: 0.45,
    directionDegrees: [-70, -28],
    animationAssetKey: 'anim.bat.flick',
  },
  {
    id: 'shot.cut',
    displayName: 'Cut',
    category: 'cross_bat',
    idealLines: ['wide_off', 'outside_off'],
    idealLengths: ['short'],
    preferredFoot: 'back',
    risk: 0.32,
    powerMultiplier: 1.0,
    timingDifficulty: 0.5,
    directionDegrees: [50, 82],
    animationAssetKey: 'anim.bat.cut',
  },
  {
    id: 'shot.pull',
    displayName: 'Pull',
    category: 'cross_bat',
    idealLines: ['outside_off', 'off_stump', 'middle', 'leg'],
    idealLengths: ['short', 'bouncer'],
    preferredFoot: 'back',
    risk: 0.38,
    powerMultiplier: 1.1,
    timingDifficulty: 0.56,
    directionDegrees: [-70, -20],
    animationAssetKey: 'anim.bat.pull',
  },
  {
    id: 'shot.hook',
    displayName: 'Hook',
    category: 'cross_bat',
    idealLines: ['off_stump', 'middle', 'leg'],
    idealLengths: ['bouncer'],
    preferredFoot: 'back',
    risk: 0.48,
    powerMultiplier: 1.12,
    timingDifficulty: 0.65,
    directionDegrees: [-88, -35],
    animationAssetKey: 'anim.bat.hook',
  },
  {
    id: 'shot.lofted_straight',
    displayName: 'Lofted Straight',
    category: 'lofted',
    idealLines: ['off_stump', 'middle'],
    idealLengths: ['full', 'good'],
    preferredFoot: 'front',
    risk: 0.48,
    powerMultiplier: 1.24,
    timingDifficulty: 0.62,
    directionDegrees: [-15, 15],
    animationAssetKey: 'anim.bat.lofted_straight',
  },
  {
    id: 'shot.lofted_off_side',
    displayName: 'Lofted Off Side',
    category: 'lofted',
    idealLines: ['wide_off', 'outside_off', 'off_stump'],
    idealLengths: ['full', 'good'],
    preferredFoot: 'front',
    risk: 0.55,
    powerMultiplier: 1.28,
    timingDifficulty: 0.68,
    directionDegrees: [18, 68],
    animationAssetKey: 'anim.bat.lofted_off',
  },
  {
    id: 'shot.lofted_leg_side',
    displayName: 'Lofted Leg Side',
    category: 'lofted',
    idealLines: ['middle', 'leg', 'wide_leg'],
    idealLengths: ['full', 'good'],
    preferredFoot: 'front',
    risk: 0.55,
    powerMultiplier: 1.28,
    timingDifficulty: 0.68,
    directionDegrees: [-72, -18],
    animationAssetKey: 'anim.bat.lofted_leg',
  },
];
