import type { CareerTierConfig } from '../types/config.types';

export const CAREER_TIERS: readonly CareerTierConfig[] = [
  {
    id: 'academy',
    minReputation: 0,
    recommendedOverall: [28, 45],
    difficultyMultiplier: 0.82,
    rewardMultiplier: 0.75,
    fanMultiplier: 0.55,
    selectorVisibility: 0.2,
    contractValueMultiplier: 0.45,
    matchesPerSeason: 8,
  },
  {
    id: 'club',
    minReputation: 80,
    recommendedOverall: [38, 55],
    difficultyMultiplier: 0.9,
    rewardMultiplier: 0.9,
    fanMultiplier: 0.7,
    selectorVisibility: 0.35,
    contractValueMultiplier: 0.65,
    matchesPerSeason: 10,
  },
  {
    id: 'district',
    minReputation: 200,
    recommendedOverall: [47, 64],
    difficultyMultiplier: 0.98,
    rewardMultiplier: 1.0,
    fanMultiplier: 0.9,
    selectorVisibility: 0.5,
    contractValueMultiplier: 0.85,
    matchesPerSeason: 12,
  },
  {
    id: 'domestic',
    minReputation: 380,
    recommendedOverall: [56, 74],
    difficultyMultiplier: 1.06,
    rewardMultiplier: 1.2,
    fanMultiplier: 1.2,
    selectorVisibility: 0.68,
    contractValueMultiplier: 1.15,
    matchesPerSeason: 14,
  },
  {
    id: 'franchise',
    minReputation: 620,
    recommendedOverall: [66, 84],
    difficultyMultiplier: 1.14,
    rewardMultiplier: 1.5,
    fanMultiplier: 1.65,
    selectorVisibility: 0.82,
    contractValueMultiplier: 1.55,
    matchesPerSeason: 16,
  },
  {
    id: 'international',
    minReputation: 820,
    recommendedOverall: [76, 95],
    difficultyMultiplier: 1.22,
    rewardMultiplier: 1.9,
    fanMultiplier: 2.2,
    selectorVisibility: 0.95,
    contractValueMultiplier: 2.2,
    matchesPerSeason: 18,
  },
];
