import { randomBytes } from 'node:crypto';

/**
 * RFC 9562 UUIDv7: 48-bit unix-ms timestamp + random bits. Time-ordered keys keep B-tree
 * inserts append-mostly on large tables. PostgreSQL 17 has no native uuidv7(), so the
 * application generates them; the column default gen_random_uuid() (v4) is only a
 * fallback for hand-written SQL.
 */
let lastMs = 0;
let sequence = 0;
export function uuidv7(at?: number): string {
  let now = at ?? Date.now();
  let counter = 0;
  // Keep ids generated by this process strictly increasing, even within one millisecond or if
  // the clock steps backwards. An explicit timestamp (tests) bypasses that state.
  if (at === undefined) {
    if (now <= lastMs) {
      now = lastMs;
      sequence += 1;
    } else {
      lastMs = now;
      sequence = 0;
    }
    counter = Math.min(sequence, 0xfff);
  }
  const bytes = randomBytes(16);
  bytes[0] = Math.floor(now / 2 ** 40) & 0xff;
  bytes[1] = Math.floor(now / 2 ** 32) & 0xff;
  bytes[2] = (now >>> 24) & 0xff;
  bytes[3] = (now >>> 16) & 0xff;
  bytes[4] = (now >>> 8) & 0xff;
  bytes[5] = now & 0xff;
  // 12-bit rand_a carries the intra-millisecond counter (RFC 9562 method 1).
  bytes[6] = 0x70 | ((counter >>> 8) & 0x0f);
  bytes[7] = counter & 0xff;
  bytes[8] = ((bytes[8] ?? 0) & 0x3f) | 0x80;
  const hex = bytes.toString('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

const UUID =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const isUuid = (value: unknown): value is string =>
  typeof value === 'string' && UUID.test(value);
